### ISSUE TITLE
== is evil in javascript

### ISSUE THREAD

**Issue by charlie-collard** [Jazqa/kwin-quarter-tiling#1]
For reference: https://stackoverflow.com/questions/359494/which-equals-operator-vs-should-be-used-in-javascript-comparisons

`==` does automatic type conversion before comparison which can lead to confusing results.

Always use `===` if you can.

EDIT: Even better, just don't use it at all if you don't need to.

For example

``` javascript
if (object.some_value === true) {
    // some code
}
```
can be replaced with
``` javascript
if (object.some_value) {
    // some code
}
```

**Comment by Jazqa** [comment]
Thanks! I've never really written Javascript and the script was a great excuse to learn the basics. I really appreciate tips like this and they are really helpful for a new "programmer" like myself . Also, this might explain some trouble I was having with `if` sentences earlier and help me fix a few issues.

I'll close this issue when I've gone through the whole code with this in mind. Once again, thanks!

**Comment by charlie-collard** [comment]
No problem, your code is actually really well written for the most part! Really clean format with lots of comments.

**Comment by Jazqa** [comment]
Cleaned all of the `==` now, very educating. There was a ton of conversion happening, because most KWin:Client-objects and their geometries couldn't be compared to the client-objects saved in the arrays without a conversion. Comparing the objects was a horrible solution anyways, so I'm comparing the id-properties of the clients instead (should have done that from the beginning, where's my common sense?).
