### ISSUE TITLE
Bug with Plasma 5.22

### ISSUE THREAD

**Issue by sardid** [Jazqa/kwin-quarter-tiling#105]
Windows that are not maximized disappear (they are still there but are somehow invisible) when the script is active. Some of them even crash. It's a very weird issue that started after I upgraded Plasma to 5.22

**Comment by kupiqu** [comment]
bump

**Comment by Jazqa** [comment]
Issue was lost in my inbox, didn’t notice until now (useful bump). Need to find time for setting up a virtual machine with 5.22. Wonder what’s suddenly broken it.

**Comment by PedroSilva8** [comment]
Can confirm this bug, the only way to make the windows show again is by right-clicking the icon on the taskbar and making it so that they appear on all virtual desktops, the only problem is that when they show up they are not on tiling mode, they are on floating mode and I can resize and move around like a normal floating window, this only happens with the git version, when using the KDE store version it doesn't happen

**Comment by Jazqa** [comment]
>…this only happens with the git version, when using the KDE store version it doesn't happen

Even the 2.0.0 store version works? There’s barely any changes between that and the latest commit.

**Comment by PedroSilva8** [comment]
I made some more testing and I noticed that of the 2 store versions the only one that works is the version with kwin on the start of the name the other version doesn't, when trying to install using the aur version it installs  the version that doesn't work
