### ISSUE TITLE
Gaps toggle

### ISSUE THREAD

**Issue by siftra** [Jazqa/kwin-quarter-tiling#11]
There are times when gaps are desired and sometimes when they aren',t and I believe the current approach for adjusting gaps is a little clunky.

Currently, if one wants to disable/enable gaps, they have to use the Meta + O/L shortcut which increases/decreases the gaps' size by 1 pixel. This is a little clunky as you have to press the shortcuts multiple times until you get rid of the gaps completely/restore them to their desired width.

I believe it would be preferable if there was a single shortcut to disable/enable gaps. This wouldn't give the user as much fine control over the gaps' size. However, in my experience, I tend to only use the gaps' size I set in the settings pane at all times anyway.

**Comment by ghost** [comment]
I agree with this. Sometimes I need just that little bit extra screen real-estate. Instead of having it as a function under the Confguration section, simply having another keybind option would work well. For instance I have Contol + Shift + Plus, or Minus to change the GAPPS size, and agree that it is a little annoying having to press that key combo a few times.

**Comment by ghost** [comment]
I think I may have just figured out how to do that . Will raise pull request.

**Comment by Jazqa** [comment]
Great idea! I've added a toggle to set gap size to 2px. I'm currently trying to avoid zero gaps because KWin automatically maximizes windows too large and it makes the script a little clunky (windows have to be constantly unmaximized for tiling). Also, if you use the +/- Gap Size shortcut, you can hold it down for a slightly faster adjustment.

Magentium-Chris, I hope you don't mind me adding it. I didn't see a pull request and I didn't know if you were at it. If your solution is better, I'll merge it for sure ;)

**Comment by ghost** [comment]
Hey!No problems here! I didn't end up figuring it out without breaking the script anyway haha.
          
            
            On Aug 2 2017, at 4:38 pm, Jasu <notifications@github.com> wrote:
            
            
              Great idea! I've added a toggle to set gap size to 2px. I'm currently trying to avoid zero gaps because KWin automatically maximizes windows too large and it makes the script a little clunky (windows have to be constantly unmaximized for tiling). Also, if you use the +/- Gap Size shortcut, you can hold it down for a slightly faster adjustment.
Magentium-Chris, I hope you don't mind me adding it. I didn't see a pull request and I didn't know if you were at it. If your solution is better, I'll merge it for sure ;)
