### ISSUE TITLE
Can't resize windows Kubuntu 22.04 Fresh install

### ISSUE THREAD

**Issue by jonkatz6** [Jazqa/kwin-quarter-tiling#111]
Had this working while using kubuntu 20.04 and it was working perfectly. Performed new installation with kubuntu 22.04 and installed quarter tiling. It seems that while quarter tiling is enabled I am not able to resize any windows like I was able to in my previous installation. Any ideas on the reason?

**Comment by jlemonde** [comment]
I'm installing this script for the first time in Kubuntu 22.04.1 and I'm having the exact same issue. Besides, it's not possible to swap open windows either. 

The user amonlinus [here](https://store.kde.org/p/1187647/) comments that it is not working for him since kde 5.22.4, so perhaps something changed in the libraries.
