### ISSUE TITLE
Keeping the default number of desktops in the long run

### ISSUE THREAD

**Issue by kupiqu** [Jazqa/kwin-quarter-tiling#15]
The script creates desktops as needed, which is great. However, when not needed, it could erase the extra ones that have been created.

Saying so because I, in general, prefer to have 2 desktops, with specific names for them, etc. I like that the script creates further ones when there is no room for the number of windows that are present, but I'd like to come back to my default, if possible, once the extra windows have been cleared.

Would that be possible?

**Comment by Jazqa** [comment]
This is one of the first issues I stumbled upon and at the time, it crashed Plasma. Another issue was identifying the desktop to remove (KWin API is at fault here, it doesn't identify the desktops, it only gives a number of total desktops), but I just figured out a way to implement this. I'll give it a shot tonight or tomorrow!

**Comment by kupiqu** [comment]
Great, thank you!

**Comment by Jazqa** [comment]
No matter how I approach the issue, Plasma always crashes. I managed to implement the feature quite nicely and it would work perfectly, if it wasn't for the Plasma crash (it actually works despite the crash, it's just slow and infeasible because Plasma has to restart itself). I'll have to investigate further, but it might be a KWin issue.

**Comment by kupiqu** [comment]
I see, thank you

**Comment by gspe** [comment]
Maybe you can look and take inspiration from this:
https://github.com/rliang/kwin-dynamic-virtual-desktops

**Comment by Jazqa** [comment]
Desktop management outscoped and removed in 2.0
