### ISSUE TITLE
tiling stops working when launching arduino ide

### ISSUE THREAD

**Issue by Munsio** [Jazqa/kwin-quarter-tiling#20]
Every time i start the arduino IDE the tiling script crashes. Tried it also with mqtt-spy (cause both are java programs) the tiling script didn't work on it but luckily it didn't crash.

Is there an debug flag or something like that to provide more information?

**Comment by Jazqa** [comment]
This is probably caused by Java, some programs are really stubborn about their window geometries and not happy to follow mine (Spotify and Kate are worth mentioning, I've had to ignore both). I'm currently on vacation (which is, of course, when the bug reports star flowing in), but I'll try to hunt this down tomorrow or the day after, might even take a few days if I'm really enjoying the weather (typically it'd be done in a day, sorry).

The only way to debug it is typing "wm konsole" to krunner (Alt + F2) and pasting the whole main.js there. If you end up doing so (don't worry if you won't, I'll fix it either way), leave it open a paste the last few lines of console output after the crash/error and I'll debug it a bit faster.

**Comment by Jazqa** [comment]
Sorry this took the whole week. Hotel's wifi was too slow and unstable to download Arduino. Anyways, it turns out Java programs are extremely difficult to recognize and deal with. I've finally found a way to completely ignore Java programs to avoid crashing, but I'm still looking for a reliable way to tile them. If you update the script, all Java programs will be excluded from tiling but the script will remain stable.

**Comment by kupiqu** [comment]
Would it be useful to create a java category in settings to disable (or enable) applications that misbehave (behave correctly)?

Saying so, because I sometimes use Matlab, which is also written in java, and so far I didn't encounter any problem with it.

Thanks!

**Comment by Jazqa** [comment]
@kupiqu, done. I added an option to completely disable all Java applications. If set to false, you can disable individual Java programs via "Ignored Programs" but it's a pain because Java programs have the weirdest class names.

**Comment by kupiqu** [comment]
Thanks

**Comment by Jazqa** [comment]
I've increased the tiling frequency for programs that change their active status often (f.ex. Java, Spotify) and added the ability to ignore all Java programs. I've looked into this issue multiple times last week and I'm afraid I can't do more, rest is up to KWin and the programs themselves. If Arduino still doesn't tile (it does for me), ignore Java or ignore Arduino (if you can't figure out how to ignore just Arduino, reply here and I'll help). Most Java programs should tile just fine now.
