### ISSUE TITLE
Floating full-size windows and inhibiting desktop tiling

### ISSUE THREAD

**Issue by Crendgrim** [Jazqa/kwin-quarter-tiling#26]
Situation: I have a fullscreen window on one (say, left) screen that is exempt from tiling (i.e. KDevelop, it behaves weirdly when it gets resized). My second (right) screen has four windows tiled, so it's full. When I open another window, it now uses the full left screen for one tile, hiding the floating window.

I would like the new window to open on another desktop instead (as if both screens were full). The best way that I can think of now is to have another category for windows, "full-size windows", that get tiled but always to a full screen (four tiles) and block any further tiles on its pane.

**Comment by Jazqa** [comment]
>I would like the new window to open on another desktop instead (as if both screens were full).

Currently, this happens if you ignore the second screen. Unfortunately, it'll be ignored on all of the other desktops as well.

>The best way that I can think of now is to have another category for windows, "full-size windows", that get tiled but always to a full screen (four tiles) and block any further tiles on its pane.

Possible, but this could be achieved without implementing yet another category by simply considering a desktop with maximized or fullscreened windows full. Of course, they'd be lacking the gaps (as they're either maximized or fullscreened) but I don't think gaps are that relevant if only a single window is present. What do you think?

**Comment by Crendgrim** [comment]
What happens then if you have four windows open (tiled 2×2) and maximize one temporarily?

**Comment by Jazqa** [comment]
It would work like it does now. Maximized and fullscreen windows would only redirect new windows to another screen/desktop as if that screen was full.

**Comment by Crendgrim** [comment]
I may miss an edge case, but that sounds like it should work just fine, yes.

**Comment by Jazqa** [comment]
Maximized and fullscreen windows now block the desktop/screen as if it was full.
 
As a warning, I ended up rewriting a **ton** of crucial code so the newest commit might contain some nasty surprises.

**Comment by Crendgrim** [comment]
In my testing so far, it seems to behave as expected.

Thanks :)
