### ISSUE TITLE
After logging in, the script doesn't work unless it's restarted

### ISSUE THREAD

**Issue by maxigaz** [Jazqa/kwin-quarter-tiling#28]
Each time I boot my computer or log out and back in, none of the windows are tiled and the keyboard shortcut for toggling tiling doesn't seem to do anything. It only starts working if I restart the script.

I have also tried using the default settings, but I get the same results.

Using Plasma 5.10.4 with Manjaro Linux x64.

**Comment by Jazqa** [comment]
As usual, I've screwed something up. Sorry. To avoid the issues caused by constant commits, I'll start versioning the releases and publishing the stable ones on Github, AUR and KDE Store soon. For now, try updating and if the problem still persists, report back. It's currently working on all of my computers. I'm sorry for making you update before really investigating the issue. Sometimes the local version of my script is ahead of the Github one and the problems might have already been fixed.

If the problem persists: 
- Are you using the compositor?
- Are you using Activities? If yes, how many?
- How many virtual desktops are you using at the start? Are any of these ignored?
- Do you have programs already open when you're logging in or are you logging back to an empty desktop?

**Comment by maxigaz** [comment]
I've just updated and I still have the issue.

> Are you using the compositor?

Yes, I use KWin.

> Are you using Activities?

No.

> How many virtual desktops are you using at the start? Are any of these ignored?

Right now "Initial desktops" has the value "4" and "Ignored desktops" has 3. (So I assume that means only desktop no. 3 is ignored, isn't it?)

> Do you have programs already open when you're logging in or are you logging back to an empty desktop?

Well, when I log in, a completely new session is started. There are a few programs that start automatically, through, minimised to the "tray icon" such as Nextcloud client, Goldendict, and Octopi.

**Comment by maxigaz** [comment]
I've managed to narrow down what could be wrong.

If I remove Goldendict from the list of programs that should be launched at start-up, the issue disappears completely. I also notice that a small window that belongs to Goldendict pops up every time it is launched telling that the installed dictionaries are being indexed. (I'll see if I can tell it not to reindex them every time.)

What's also interesting is that if I start Goldendict manually, it doesn't break tiling, only if it is launched automatically on logging in.

**Comment by Jazqa** [comment]
Yep. Autostart of Goldendict is probably messing with the script's init function. I downloaded Goldendict as well and enabled "Start with system", "Start to system tray" and "Close to system tray" settings. The script is still starting properly for me.

**Comment by Jazqa** [comment]
Any luck now? Script's start should be more reliable and I've fixed a bug with particular type of programs (if KWin considered Goldendict a `dialog`, this issue is solved).

**Comment by maxigaz** [comment]
It's working now, even with GD launched automatically! Thank you very much!
