### ISSUE TITLE
Resizing a Window with Alt + left mouse when maximised breaks tiling 

### ISSUE THREAD

**Issue by ghost** [Jazqa/kwin-quarter-tiling#3]
If you make a window full screen by accident (or purposefully) and then right click + left mouse to resize the window, it will come out of full screen mode but then not tile correctly. This is most probably related to how Plasma shows Maximised and Un-maximised windows.

**Comment by Jazqa** [comment]
Full-screen is (thanks to KWin) completely different than maximized. Since I never use full-screen myself, I've completely forgotten the full-screening. Fixing this as soon as I get on my computer. Thanks for reporting!

**Comment by Jazqa** [comment]
Okay, finally on my computer again! Did you mean the scenario in the picture below? 

Edit: I should have read the title. Got it now, the problem is the same as the scenario in the picture though. For some reason resizing a maximized client doesn't trigger the "unmaximize" signal. Fixing it asap!

![Picture](http://i.imgur.com/YzyISBp.png)
