### ISSUE TITLE
Would it be possible to tile to more than quarters instead of changing the vd count ?

### ISSUE THREAD

**Issue by eizanprime** [Jazqa/kwin-quarter-tiling#30]
The script is really awesome, and it has I feel even more potential ! Do you think it might be possible to tile to infinity on one screen ?

**Comment by Jazqa** [comment]
I think there is [a tiling script for that](https://github.com/faho/kwin-tiling), although I've never tried it.

That being said, I have thought about supporting more windows by adding a shortcut that would split the active tile in two in order to make space for a new window. If windows were not manually split, the script would function as it does now.

I have not attempted to implement this yet and it is most likely a huge job. I will priorize the current issues and bugs in order to make a stable version of the script available before doing any drastic changes such as this. 

To answer your question: I'll try to implement it but it may take weeks or even a month or two depending on how busy I am. I prefer stability and clarity over features so if the feature ends up making the script too buggy or complicated, I might not implement it.

**Comment by eizanprime** [comment]
I see ! Your script is by far the best!

This shortcut idea is very good, I hope you can implement it!

**Comment by haadr** [comment]
Hi and thanks for an awesome script! First tiling script that's worked for me.

Would this issue also cover having a layout of for instance three windows/tiles next to each other? (instead of only being able to have 2 in one "column" and a third being the second column)

**Comment by Jazqa** [comment]
@haadr, glad you like the script! Support for multiple layouts is a different issue but I've thought about implementing the feature for a while now. I've been busy lately, but once I can find some free time, I'll try to implement support for different layouts (horizontal 2 + 2, vertical 1 + 3, horizontal 1 + 3).

Both of these issues require quite a lot of work but both are definitely on my todo-list. Layouts are probably coming first as they're easier to implement and if I don't implement them first, I might have to adjust the splitting feature to the layouts separately.
