### ISSUE TITLE
Wrong width of a new window

### ISSUE THREAD

**Issue by andreyorst** [Jazqa/kwin-quarter-tiling#34]
_(Not only height behavior can confuse me)_
_(I **love** images)_

Plugin settings:
![image](https://user-images.githubusercontent.com/19470159/31145978-e8579d08-a88d-11e7-9a6d-21084c36eae4.png)

So if i open 2 apps like so
![image](https://user-images.githubusercontent.com/19470159/31145596-db2dabd2-a88c-11e7-80f3-489388f094b0.png)
And will open third one it will split in half our righ one like intented:
![image](https://user-images.githubusercontent.com/19470159/31145627-f7c03d96-a88c-11e7-9d41-e4dc518c61e9.png)
But if our right app width is less then left app width, like so:
![image](https://user-images.githubusercontent.com/19470159/31145671-1d1e1dd8-a88d-11e7-914c-a5205be71f42.png)
A new split will expand right window width:
![image](https://user-images.githubusercontent.com/19470159/31145715-3cda45a2-a88d-11e7-8d91-0b54417e236c.png)

or on a screencast (i can't create gif with ssr, and don't have any software to create gif from mkv):
[width.zip](https://github.com/Jazqa/kwin-quarter-tiling/files/1353651/width.zip)

**Comment by andreyorst** [comment]
Oh and same works if i want to create 4th window and my left column is < then right one

**Comment by Jazqa** [comment]
This is actually intentional. However, it should not be happening if "Autosize" is disabled. It's a silly feature but I actually use it quite a lot. I like the fact that new windows made space for themselves and reset the width of the tile if it was smaller than the default. 

Now that I think of it, I understand the confusion though. **I'll rework the whole damn "Autosize" feature first thing tomorrow** (day off, yay!). It's nothing but inconsistent, messy and buggy pile of garbage. I'll simplify the tiling to work "as expected" and get rid of the weird tweaks.

**Comment by andreyorst** [comment]
> I'll rework the whole damn "Autosize" feature first thing tomorrow (day off, yay!)

I wish i knew JS, to help with the development, but i don't

**Comment by Jazqa** [comment]
It's not a huge job and I actually enjoy it. I might rework the whole script once I'm done with my bachelor's thesis (~2-4 weeks).

**Comment by Jazqa** [comment]
This does not happen anymore. Horizontal autosizing has been removed.
