### ISSUE TITLE
Open specific app on a specific virtual desktop

### ISSUE THREAD

**Issue by andreyorst** [Jazqa/kwin-quarter-tiling#36]
For example I know, that I don't want to open gimp or inkscape in a small tile, I need to switch to empty desktop (or create one), open gimp and wait till it loads, cause if I switch desktop it will open on _current_ one. Instead of doing this I may predefine that gimp open on six desktop only, and mpv on another one and so on. So when I open any app that should use as much of screen space as possible, I would definitely know where this app opened and that it will not break my current desktop setup.

**Comment by Jazqa** [comment]
This is already a feature in KDE and it works with the script. Just make sure you start the script with the wanted amount of desktops (I don't know what happens if the number of desktops is smaller than the desktop you wish to use) and right click the title bar of the program and go to `More Actions` > `Special Application Settings...` > `Size & Position` > `Desktop` > `Apply Initially`.

**Comment by andreyorst** [comment]
well closing then

**Comment by Valeriyspk** [comment]
It seems, that script broke this KDE functional for me.
I had used this KDE settings before kwin-quarter-tiling installaion, and they was completely ok.
But today, after quarter-tiling installation, apps started to open up on first desktop, even if they have "special settings".
I tried to reset and restore settings, and also to configure it in some different way, to make them work with script enabled, but with no luck.
If I set "force" setting in "special settings"->"desktop", apps opens in correct desktop, but, in this case, they are floating, not tiled. 

I'm using Manjaro (KDE), script was installed from AUR.
