### ISSUE TITLE
Can't see Quarter Tiling in configuration interface.

### ISSUE THREAD

**Issue by Nifled** [Jazqa/kwin-quarter-tiling#37]
I decided to install this via the interface in `System Settings` under `Window Management` and `Get New Scripts`, since I'm having trouble doing it via the command line, and ended up installing it successfully (apparently). The problem is, now that I've installed it, `Quarter Tiling` doesn't show up on the `Manage KWin scripts section` like in the screenshots in this repo. All I see are the default options.

**Comment by Jazqa** [comment]
Do you mean the Quarter Tiling script is not – at all – visible in the `Manage KWin Scripts`or is it just the configuration menu for the script missing? If it's only the configuration menu that's missing, it's a known issue when installing KWin Scripts via the KDE Settings. Don't worry though, you should be able to fix it with two commands.

```
mkdir -p ~/.local/share/kservices5

ln -sf ~/.local/share/kwin/scripts/quarter-tiling/metadata.desktop ~/.local/share/kservices5/kwin-script-quarter-tiling.desktop
```

If you installed the script as root, the paths would be `/usr/share/` instead of `~/.local/share/`

**Comment by Nifled** [comment]
For some reason it's the Quarter Tiling script is not visible in the `Manage KWin Scripts` at all. I go into the KDE Store and it appears as 'installed', and even has an option to uninstall, but I don't see it under the actual menu. 

This is a fresh KDE Neon install btw, I'll try executing the commands you mentioned as soon as I can. Thanks for the reply!

**Comment by Jazqa** [comment]
No problem, I'll gladly help you get the script working. Never hesitate to ask questions :wink: 

Anyways, what does `ls ~/.local/share/kwin/scripts` print? I wonder if the script got properly installed as the KDE Store is (at least in my experience) a little unreliable.
