### ISSUE TITLE
Trying to move client to a screen with a fullscreen application already running removes the client.

### ISSUE THREAD

**Issue by barisdemirdelen** [Jazqa/kwin-quarter-tiling#41]
Hello,

I have a 3 monitor setup, and one of them always runs a fullscreen application. I use move to next/previous screen shortcuts a lot, but sometimes i accidentally try to move a window to the screen with the fullscreen application. This removes the client from tiling, until i restart the application again. I fixed my setup with commenting out the [removeClient call here](https://github.com/Jazqa/kwin-quarter-tiling/blob/d492b648c62386fd732a7beaf3eccfed72479348/contents/code/main.js#L1165).

I was wondering if there is a reason to remove the client there, and if there is maybe we can find another solution for this.

Great script by the way, many thanks.

Cheers

**Comment by Jazqa** [comment]
Sorry for a slow response. Fullscreen applications "block" the screen. I've chosen to remove the clients in such situations for consistency – I personally don't think tiling on top of a fullscreen client is desirable behavior. **However, the client should go back to tiling when moved from a blocked screen back to a screen without a fullscreen application**, so that's a bug. 

Good job reading my spaghetti code by the way, removing the `removeClient` call fixes the issue but allows tiling on blocked and ignored screens. Removing the `if (client.included)` condition a few lines up should fix this though. I'm already in bed, but I have a few hours tomorrow to fix this issue and multiple other ones that have been piling up while I've been busy.

**Comment by barisdemirdelen** [comment]
Thanks for the feedback. It makes sense that nothing broke for me because i don't have any ignored screens. The code itself isn't that bad to get around. Lets just say that i have seen much worse :)

On an unrelated question, i am not at all familiar with developing kwin scripts, and i have another rare bug with this one i would like to track. Can i ask how you develop and debug this script?

I found that i could use 

    qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.showInteractiveConsole

to start an editor and execute the script but its not the most convenient way for me.

**Comment by Jazqa** [comment]
I'm afraid the interactive console is the best way to debug KWin Scripts. What kind of bug are you experiencing?

**Comment by barisdemirdelen** [comment]
Sometimes when i move a window to another screen with mouse, and leaving the mouse on top of the screen so the window moves to the screen and fullscreens at the same time, it breaks tiling. But i haven't tested yet as to in which circumstances this occurs.

**Comment by Jazqa** [comment]
Fixed. Quarter Tiling shortcuts now move windows across screens even if the screens are ignored or blocked. However, you may not notice the change as fullscreen programs are displayed above others, so the window moved to the same screen will be located under the fullscreen program.

**Comment by barisdemirdelen** [comment]
I can confirm it works now, thanks!
