### ISSUE TITLE
Automatically disable tiling for fullscreen windows

### ISSUE THREAD

**Issue by Crendgrim** [Jazqa/kwin-quarter-tiling#7]
When you have a window that wants fullscreen, it still gets tiled and forced into a tile when this script is running. I noticed this with mpv (switching to fullscreen didn't work until I manually disabled tiling) as well as with games, specifically CS:GO (which would start up tiled). It would be nice if fullscreen windows would be automatically exempt from the tiling.

**Comment by Jazqa** [comment]
This is obvious, can't believe I've missed this. Fix coming soon. Once again, thanks for the help!

**Comment by Jazqa** [comment]
Any improvement? I tried it with the only fullscreen game I had (Stardew Valley) and it seemed to work.

**Comment by kupiqu** [comment]
I tested this in SMPlayer (with the option open videos in fullscreen) and works. There is however a caveat, when I click on a video SMPlayer is launched, initially following tiling for a frac of a sec and rapidly going to fullscreen. Not sure if the initial tiling is SMPlayer's responsibility or not, but I wanted to help testing this (I don't have any other fullscreen application).

**Comment by Crendgrim** [comment]
I've been testing this a bit with different programs, and it seems to work now. Thanks!
I have not seen the behaviour kupiqu described.

**Comment by kupiqu** [comment]
Great! This must be sth coming from SMPlayer itself then...

**Comment by Jazqa** [comment]
@kupiqu, SMPlayer opening itself as a regular (non-fullscreened) window and then fullscreening itself a moment later is the most likely cause. 

There's still some tweaking to do with fullscreen/maximized/minimized clients due to KWin API treating them so differently, but I'll probably fix it all tonight (plus Konqueror, I didn't drop a comment there as you'll probably see this too). I doubt it will change the behaviour of SMPlayer though.

@Crendgrim, glad to hear that! Stardew Valley and Civilization V were the only programs I could get to launch with fullscreen enabled, so I couldn't test it thoroughly.

**Comment by Jazqa** [comment]
Did some improvements on minimizing, maximizing and fullscreening tonight. All of those clients should be ignored until unminimized, unmaximized or unfullscreened.
