### ISSUE TITLE
Remove empty desktop

### ISSUE THREAD

**Issue by Sparsa** [Jazqa/kwin-quarter-tiling#79]
This is the best tiling script I've tried for KDE. But, it will be really nice if it automatically removes empty desktop, i.e. when I close all the windows of a desktop.

**Comment by ghost** [comment]
It's supposed to , but recently I've noticed it does not :(

**Comment by Jazqa** [comment]
Last I tried, it crashed KWin when removing the desktop automatically, so I had to disable the feature.

**Comment by Jazqa** [comment]
As of 5.17, removing a desktop with the script still crashes KWin.

**Comment by Jazqa** [comment]
Desktop management outscoped and removed in 2.0

**Comment by Sparsa** [comment]
So version 2 released?

**Comment by Jazqa** [comment]
Yes. I rewrote the script and cut some of the features to improve stability. Creating and removing desktops was very unstable, so I just decided to toss the feature. The script still has an option to move within the existing desktops, it just doesn’t create or remove any on its own.

Although version 2.0 isn’t anything fancy, it should have the essential features of 1.0 with improved stability. More importantly, the code is much cleaner so new features, bug fixes etc. are easier to implement and release instead of leaving the project in an unmaintained state like I ended up doing with the first version.
